import type {
  AppData,
  CompanyView,
  CustomerView,
  EquipmentView,
  ServiceCatalogView,
  ServiceOrderView,
} from "@/types/domain";

export const demoCompany: CompanyView = {
  companyName: "Deyvid Infotech",
  document: "00.000.000/0001-00",
  phone: "(11) 3333-2026",
  whatsapp: "(11) 99999-2026",
  instagram: "@deyvidinfotech",
  email: "contato@deyvidinfotech.local",
  address: "Av. Tecnologia, 256",
  city: "São Paulo",
  state: "SP",
  logoUrl: "/logo.png",
  primaryColor: "#0066FF",
};

export const demoCustomers: CustomerView[] = [
  {
    id: "customer-marina",
    name: "Marina Costa",
    document: "123.456.789-10",
    phone: "(11) 98811-2200",
    whatsapp: "(11) 98811-2200",
    email: "marina@example.local",
    address: "Rua das Flores, 120",
    city: "São Paulo",
    state: "SP",
    notes: null,
    equipmentCount: 1,
    orderCount: 1,
    purchaseCount: 1,
    registrationCount: 1,
    latestOrderId: "order-001",
    latestOrderNumber: "OS-2026-000001",
    createdAt: "2026-07-12T13:10:00.000Z",
  },
  {
    id: "customer-rafael",
    name: "Rafael Mendes",
    document: "987.654.321-00",
    phone: "(11) 97742-1010",
    whatsapp: "(11) 97742-1010",
    email: "rafael@example.local",
    address: null,
    city: "Osasco",
    state: "SP",
    notes: "Prefere contato por WhatsApp.",
    equipmentCount: 1,
    orderCount: 1,
    purchaseCount: 1,
    registrationCount: 1,
    latestOrderId: "order-002",
    latestOrderNumber: "OS-2026-000002",
    createdAt: "2026-07-16T16:40:00.000Z",
  },
  {
    id: "customer-nova",
    name: "Nova Arquitetura Ltda.",
    document: "45.678.901/0001-22",
    phone: "(11) 3222-8800",
    whatsapp: "(11) 98800-1188",
    email: "ti@novaarquitetura.example",
    address: null,
    city: "Barueri",
    state: "SP",
    notes: "Equipamentos corporativos.",
    equipmentCount: 1,
    orderCount: 2,
    purchaseCount: 2,
    registrationCount: 1,
    latestOrderId: "order-003",
    latestOrderNumber: "OS-2026-000003",
    createdAt: "2026-07-18T10:20:00.000Z",
  },
];

export const demoEquipment: EquipmentView[] = [
  {
    id: "equipment-dell",
    customerId: "customer-marina",
    customerName: "Marina Costa",
    type: "NOTEBOOK",
    brand: "Dell",
    model: "Inspiron 15 5510",
    serialNumber: "DL-5510-2481",
    color: "Prata",
    deliveredAccessories: "Fonte original 65W",
    physicalCondition: "Marcas leves de uso na tampa",
    reportedDefect: "Desliga sozinho após alguns minutos de uso.",
    notes: null,
    orderCount: 1,
    createdAt: "2026-07-28T12:00:00.000Z",
  },
  {
    id: "equipment-samsung",
    customerId: "customer-rafael",
    customerName: "Rafael Mendes",
    type: "SMARTPHONE",
    brand: "Samsung",
    model: "Galaxy S22",
    serialNumber: "SM-S901B-1188",
    color: "Preto",
    deliveredAccessories: "Capa protetora",
    physicalCondition: "Tela sem trincas, riscos na lateral",
    reportedDefect: "Não reconhece o cabo de carregamento.",
    notes: null,
    orderCount: 1,
    createdAt: "2026-07-27T14:30:00.000Z",
  },
  {
    id: "equipment-lenovo",
    customerId: "customer-nova",
    customerName: "Nova Arquitetura Ltda.",
    type: "NOTEBOOK",
    brand: "Lenovo",
    model: "ThinkPad E14",
    serialNumber: "PF-3JX9-782",
    color: "Preto",
    deliveredAccessories: "Fonte e mochila",
    physicalCondition: "Bom estado geral",
    reportedDefect: "Sistema lento e aquecimento acima do normal.",
    notes: "Patrimônio interno 042.",
    orderCount: 2,
    createdAt: "2026-07-26T09:30:00.000Z",
  },
];

export const demoServices: ServiceCatalogView[] = [
  {
    id: "service-cleaning",
    name: "Limpeza interna completa",
    category: "Limpeza interna",
    description: "Limpeza de placa, coolers, dissipadores e carcaça.",
    minimumValue: 120,
    maximumValue: 180,
    estimatedTime: "2 a 3 horas",
    active: true,
  },
  {
    id: "service-thermal",
    name: "Troca de pasta térmica",
    category: "Troca de pasta térmica",
    description: "Substituição da interface térmica do processador.",
    minimumValue: 80,
    maximumValue: 140,
    estimatedTime: "1 a 2 horas",
    active: true,
  },
  {
    id: "service-format",
    name: "Formatação e otimização",
    category: "Formatação",
    description: "Instalação limpa, drivers e atualizações.",
    minimumValue: 150,
    maximumValue: 250,
    estimatedTime: "4 a 8 horas",
    active: true,
  },
  {
    id: "service-part",
    name: "Troca de componente",
    category: "Troca de peças",
    description: "Diagnóstico e substituição de componente com teste.",
    minimumValue: 100,
    maximumValue: 450,
    estimatedTime: "Sob diagnóstico",
    active: true,
  },
  {
    id: "service-recovery",
    name: "Recuperação de arquivos",
    category: "Recuperação de arquivos",
    description: "Tentativa de recuperação lógica de dados.",
    minimumValue: 250,
    maximumValue: 850,
    estimatedTime: "1 a 5 dias úteis",
    active: true,
  },
];

const baseOrder = {
  customerDocument: null,
  customerPhone: null,
  customerWhatsapp: null,
  customerAddress: null,
  customerCity: null,
  customerState: null,
  equipmentSerialNumber: null,
  equipmentColor: null,
  deliveredAccessories: null,
  physicalCondition: null,
  equipmentDescription: null,
  technicalDiagnosis: null,
  performedService: null,
  partsUsed: null,
  internalNotes: null,
  customerNotes: null,
  partsValue: 0,
  discount: 0,
  surcharge: 0,
  paymentMethod: null,
  expectedDeliveryDate: null,
  completedAt: null,
  pickedUpAt: null,
  technicianName: "Deyvid Silva",
};

export const demoOrders: ServiceOrderView[] = [
  {
    ...baseOrder,
    id: "order-001",
    number: "OS-2026-000001",
    customerId: "customer-marina",
    customerName: "Marina Costa",
    customerDocument: "123.456.789-10",
    customerPhone: "(11) 98811-2200",
    customerWhatsapp: "(11) 98811-2200",
    equipmentId: "equipment-dell",
    equipmentType: "NOTEBOOK",
    equipmentLabel: "Dell Inspiron 15 5510",
    equipmentBrand: "Dell",
    equipmentModel: "Inspiron 15 5510",
    equipmentSerialNumber: "DL-5510-2481",
    equipmentColor: "Prata",
    deliveredAccessories: "Fonte original 65W",
    physicalCondition: "Marcas leves de uso na tampa",
    status: "IN_ANALYSIS",
    priority: "HIGH",
    reportedDefect: "Desliga sozinho após alguns minutos de uso.",
    technicalDiagnosis:
      "Possível superaquecimento; testes térmicos em andamento.",
    requestedService: "Diagnóstico completo e orçamento.",
    serviceValue: 180,
    totalValue: 180,
    paidValue: 0,
    pendingValue: 180,
    entryDate: "2026-07-30T12:00:00.000Z",
    expectedDeliveryDate: "2026-08-03T18:00:00.000Z",
    createdAt: "2026-07-30T12:00:00.000Z",
    updatedAt: "2026-07-30T13:20:00.000Z",
  },
  {
    ...baseOrder,
    id: "order-002",
    number: "OS-2026-000002",
    customerId: "customer-rafael",
    customerName: "Rafael Mendes",
    customerDocument: "987.654.321-00",
    customerPhone: "(11) 97742-1010",
    customerWhatsapp: "(11) 97742-1010",
    equipmentId: "equipment-samsung",
    equipmentType: "SMARTPHONE",
    equipmentLabel: "Samsung Galaxy S22",
    equipmentBrand: "Samsung",
    equipmentModel: "Galaxy S22",
    equipmentSerialNumber: "SM-S901B-1188",
    equipmentColor: "Preto",
    deliveredAccessories: "Capa protetora",
    physicalCondition: "Tela sem trincas, riscos na lateral",
    status: "READY_FOR_PICKUP",
    priority: "NORMAL",
    reportedDefect: "Não reconhece o cabo de carregamento.",
    technicalDiagnosis: "Conector danificado por oxidação leve.",
    requestedService: "Reparo do conector USB-C.",
    performedService: "Substituição do conector e limpeza da placa.",
    partsUsed: "1 conector USB-C compatível",
    serviceValue: 180,
    partsValue: 90,
    totalValue: 270,
    paidValue: 270,
    pendingValue: 0,
    paymentMethod: "PIX",
    entryDate: "2026-07-28T13:30:00.000Z",
    completedAt: "2026-07-30T10:00:00.000Z",
    createdAt: "2026-07-28T13:30:00.000Z",
    updatedAt: "2026-07-30T10:00:00.000Z",
  },
  {
    ...baseOrder,
    id: "order-003",
    number: "OS-2026-000003",
    customerId: "customer-nova",
    customerName: "Nova Arquitetura Ltda.",
    customerDocument: "45.678.901/0001-22",
    customerPhone: "(11) 3222-8800",
    customerWhatsapp: "(11) 98800-1188",
    equipmentId: "equipment-lenovo",
    equipmentType: "NOTEBOOK",
    equipmentLabel: "Lenovo ThinkPad E14",
    equipmentBrand: "Lenovo",
    equipmentModel: "ThinkPad E14",
    equipmentSerialNumber: "PF-3JX9-782",
    equipmentColor: "Preto",
    deliveredAccessories: "Fonte e mochila",
    physicalCondition: "Bom estado geral",
    status: "IN_MAINTENANCE",
    priority: "URGENT",
    reportedDefect: "Sistema lento e aquecimento acima do normal.",
    technicalDiagnosis: "Cooler obstruído e SSD com pouco espaço livre.",
    requestedService: "Limpeza, troca de pasta térmica e otimização.",
    serviceValue: 320,
    totalValue: 320,
    paidValue: 160,
    pendingValue: 160,
    paymentMethod: "PIX",
    entryDate: "2026-07-29T12:30:00.000Z",
    expectedDeliveryDate: "2026-08-01T21:00:00.000Z",
    createdAt: "2026-07-29T12:30:00.000Z",
    updatedAt: "2026-07-30T11:40:00.000Z",
  },
  {
    ...baseOrder,
    id: "order-004",
    number: "OS-2026-000004",
    customerId: "customer-nova",
    customerName: "Nova Arquitetura Ltda.",
    customerDocument: "45.678.901/0001-22",
    customerPhone: "(11) 3222-8800",
    customerWhatsapp: "(11) 98800-1188",
    equipmentId: "equipment-lenovo",
    equipmentType: "NOTEBOOK",
    equipmentLabel: "Lenovo ThinkPad E14",
    equipmentBrand: "Lenovo",
    equipmentModel: "ThinkPad E14",
    status: "COMPLETED",
    priority: "NORMAL",
    reportedDefect: "Falha na inicialização do sistema.",
    technicalDiagnosis: "Arquivos de inicialização corrompidos.",
    requestedService: "Reparo do sistema sem formatação.",
    performedService: "Reparo da inicialização e atualização do sistema.",
    serviceValue: 190,
    totalValue: 190,
    paidValue: 190,
    pendingValue: 0,
    paymentMethod: "CREDIT_CARD",
    entryDate: "2026-07-22T12:00:00.000Z",
    completedAt: "2026-07-23T17:00:00.000Z",
    pickedUpAt: "2026-07-24T18:00:00.000Z",
    createdAt: "2026-07-22T12:00:00.000Z",
    updatedAt: "2026-07-24T18:00:00.000Z",
  },
];

export const demoAppData: AppData = {
  company: demoCompany,
  customers: demoCustomers,
  equipment: demoEquipment,
  services: demoServices,
  orders: demoOrders,
};
